apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: app
spec:
   containers:
     - name: web
       image: neodim5/kube-intro:latest
       volumeMounts:
         - name: app
           mountPath: /app
   volumes:
     - name: app
       emptyDir: {}
