apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: app
spec:
   containers:
     - name: web
       image: neodim5/kube-intro:v0.0.1
       # --- BEGIN ---
       readinessProbe: # Добавим проверку готовности
         httpGet: # веб-сервера отдавать
           path: /index.html # контент
           port: 80
       # --- END ---
       volumeMounts:
         - name: app
           mountPath: /app
   initContainers:
     - name: init
       image: busybox:1.36
       command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
       volumeMounts:
         - name: app
           mountPath: /app
   volumes:
     - name: app
       emptyDir: {}
